[env:lilygo-t-hmi]
platform = espressif32
board = esp32s3-devkitc-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.flash_mode = qio
board_build.flash_freq = 80m

lib_deps =
    TFT_eSPI
    TOTP
    WiFi
    WebServer
    DNSServer
    Preferences

upload_port = COM3
monitor_port = COM3

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM